### PR TITLE
Allow library location to be chosen

### PR DESCRIPTION
**Pull request by matteke-games**
As said in #220 here is the pull request, please review it and tell me if any more changes should be made

### CODE REVIEW

**Comment by matteke-games** [comment]
Hmmm, maybe I should change the other projects too so the appveyor build succeeds

**Comment by spazzarama** [comment]
Not keen on changing the public signature of that method, however adding it as a property on the Config static class instead?

Note the best from a design stance, but at least the impact is low.

**Comment by matteke-games** [comment]
Hmmm okay

**Comment by matteke-games** [comment]
Just so I'm sure I understand it correctly. I add a property to the EasyHook.Config static class called: "HelperLibrariesLocation" which will then be used instead of "Path.GetDirectoryName(typeof(Config).Assembly.Location)" and either the property returns the user defined location if any or it returns the same path the current function would return

**Comment by spazzarama** [comment]
Correct

**Comment by matteke-games** [comment]
It became a bit of a mess but this should do it

**Pull request merged**
